# This workflow will install Python dependencies, run tests, and push changes to the repository
name: fdom and weather forecaster

on:
  schedule:
    - cron: '1 */1 * * *'  # Runs every hour at the first minute

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test the python code
      run: |
        python app_ensemble_fdom.py
    - name: Commit and push files
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --local user.email "damebet@gmail.com"
        git config --local user.name "danielmerbet"
        git add --all
        git commit -m "auto commit $(date)" || echo "No changes to commit"
        git remote set-url origin https://danielmerbet:${PAT_TOKEN}@github.com/danielmerbet/fdom_weather_app.git
        git push origin main
